<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V6QH7CG" failures="1" tests="7" name="test2+test3" time="32.314" errors="0" timestamp="2021-10-18T21:48:49 IDT">
  <testcase classname="Tests.HomeDelivery" name="CityNotValidTest" time="0.554">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at Japanika.Functions.HomeDeliveryNotValid(Functions.java:38)
at Tests.HomeDelivery.CityNotValidTest(HomeDelivery.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- CityNotValidTest -->
  <testcase classname="Tests.HomeDelivery" name="CityValidTest" time="12.697"/>
  <testcase classname="Tests.HomeDelivery" name="AddMeal_1Test" time="3.929"/>
  <testcase classname="Tests.HomeDelivery" name="AddMeal_2Test" time="2.629"/>
  <testcase classname="Tests.HomeDelivery" name="ChangeMealDetailTest" time="4.614"/>
  <testcase classname="Tests.HomeDelivery" name="RemoveItemTest" time="2.253"/>
  <testcase classname="Tests.HomeDelivery" name="CleanCartTest" time="0.252"/>
</testsuite> <!-- test2+test3 -->
